algoritmo "somaDosNumeros"
var
  a: real
  b: real
  soma: real

inicio
      // Pede o valor de a
      Escreva("Por favor, digite o valor de A: ")
      Leia(a)
      
      // Pede o valor de b
      Escreva("Por favor, digite o valor de B: ")
      Leia(b)
      
      // Soma o valor de a + b e guarda na variável soma
      soma <- a + b
      Escreva("A soma de ", a, " + ", b, " é ", soma) // mostra o resultado ao usuário
fimalgoritmo
