algoritmo "numerosIguaisOuDiferentes"
// Ler 3 números e dizer se são iguais ou diferentes
var numero1, numero2, numero3: inteiro

inicio
      Escreva("NÚMERO 1: ")
      Leia(numero1)
      
      Escreva("NÚMERO 2: ")
      Leia(numero2)
      
      Escreva("NÚMERO 2: ")
      Leia(numero3)
      
      se (numero1 = numero2) e (numero2 = numero3) entao
         Escreva("São números IGUAIS")
      senao
         Escreva("São números DIFERENTES")
      fimse
fimalgoritmo
