algoritmo "contaPares"
var contador, valor: inteiro

inicio
      // Pede ao usuário inserir um valor
      Escreva("Digite um valor: ")
      Leia(valor)
      
      // Método 01 - Passo de 2 em 2
      // Para contador <- 0 ate valor passo 2 faca
      
      // Método 02 - Veriricando a cada execução seo contador é par
      Para contador <- 0 ate valor faca
         se (contador % 2 = 0) entao
            Escreval(contador)
         fimse
      fimpara
fimalgoritmo
