algoritmo "combinacoes"
var comeco, fim, c1, c2: inteiro

inicio
   // Pede ao usuário o número que começa
   Escreva("COMEÇO: ")
   Leia(comeco)

   // Pede ao usuário o número que termina
   Escreva("FIM: ")
   Leia(fim)

   // Exibe os números combinados formatados
   Para c1 <- comeco ate fim faca
      Para c2 <- comeco ate fim faca
         Escreva(c1)
         Escreva(c2)
         Escreval("")
      fimpara

      Escreval("")
   fimpara
fimalgoritmo
